### ISSUE TITLE
I don't think the preamp section does what it should do

### ISSUE THREAD

**Issue by mrnuke** [ohdsp/ADC-PCM4202#1]
I'd expect the preamp to the ADC to do several things, of which:

1. Shift an input voltage of 0V to Vcom
2. Maintain phase relationship between input and output signals

I'll take one half of the preamp for demonstration purposes:
 
![half-preamp](https://user-images.githubusercontent.com/2610559/42740208-9449cb66-8869-11e8-80a9-dd63dd11ce84.png)

Under normal operating conditions Vc = V+, and the opamp does its thing to keep V- = Vc. Looking at a current going throgh R411 and R419 we get:

![current](https://user-images.githubusercontent.com/2610559/42740302-471ef59e-886b-11e8-90d3-ffb8b744c8a9.gif)

We can solve this for Vo, and rearrange things a bit to get:

![voutput](https://user-images.githubusercontent.com/2610559/42740356-ffa16f8e-886b-11e8-8f7b-5739c063d884.gif)

It could be that I'm just reading the schematic completely wrong, but I doubt it. This fails point (1) because it applies a non-unity gain to Vcom. It fails point (2) because it inverts the phase of the signal -- negative gain wrt Vi.

(2) is easy to fix, just swap the ANAL+/- connections. 
(1) can be fixed by applying Vcom to a summing junction at the inverting input. However, in that case, it's probably better to use an instrumentation amplifier topology, and Vcom might need to be buffered

**Comment by ohdsp** [comment]
C414 gives unity gain at DC. See examples for chips like the PCM4220.

**Comment by mrnuke** [comment]
Oh, DUH. You are right. I can't ignore C414 like I did, because it blocks DC currents. Thank you for clarifying this, and my apologies for raising a false alarm. There's still the phase reversal issue (which is correctly handled in the PCM4220 example circuit).

**Comment by ohdsp** [comment]
PCM4220 has both inverting/non-inverting options as examples. You do not need to maintain the phase, and with a differential input who's to say it was wired correctly anyway. With a DSP in the middle you can just hit the invert button. There many technical arguments for inverting/non-inverting. In this instance I can achieve gains <1 if needed.
